# Generated by Django 3.2.11 on 2022-01-28 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('about_me', models.TextField()),
                ('address', models.CharField(max_length=150)),
                ('blog_url', models.CharField(max_length=200, null=True)),
                ('facebook_profile', models.CharField(max_length=120, null=True)),
                ('twitter_profile', models.CharField(max_length=120, null=True)),
                ('linkedin_profile', models.CharField(max_length=120, null=True)),
                ('portfolio', models.CharField(max_length=120, null=True)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
