# Generated by Django 3.2.11 on 2022-01-29 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='portfolio',
            new_name='portfolio_url',
        ),
    ]
